### ISSUE TITLE
Make volume slider adjust sample volume instead of playback volume

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/lsdpatch#47]
IMHO the current volume slider is not that useful, my computer anyway has increase/decrease volume buttons that are easay to reach :-)

Adjusting sample volume would be useful, in case some sample in a kit should not be at max volume!

**Comment by Eiyeron** [comment]
The slider was originally done because the playback would happen at 100%, usually resulting in my speakers full blasting sample (or garbage if I was breaking the sample code at the point) where the rest of the programs were outputting at a lower volume, even on a similar volume setting.

But yeah, adding a gain slider might help people a bit.

**Comment by jkotlinski** [comment]
fixed
