### ISSUE TITLE
Loading 2 fonts with similar names replaces both fonts

### ISSUE THREAD

**Issue by defensem3ch** [jkotlinski/lsdpatch#63]
Loading one font e.g. `TEST.png` into slot 2, then loading a new font e.g. `TEST2.png` replaces both TEST fonts with `TEST2.png`

**Comment by jkotlinski** [comment]
Could this be due to a Java bug with the editable fontname combo box? If several values in the list have the same value, it will only be possible to select the first. This leads to confusing behaviors.

For the palette editor, I worked around this by appending an incrementing number to duplicate list entries.

**Comment by defensem3ch** [comment]
I think that's the case here too. Incrementing number would probably be a good solution
